# Generated by Django 4.0.5 on 2022-06-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=10)),
                ('brand_country', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('brand_name',),
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=20)),
                ('car_color', models.CharField(blank=True, choices=[('black', 'black'), ('red', 'red'), ('gray', 'gray'), ('biege', 'biege'), ('green', 'green'), ('dark-gray', 'dark-gray'), ('blue', 'blue'), ('white', 'white')], default='black', max_length=20, null=True)),
                ('car_price', models.PositiveIntegerField(verbose_name='Цена в USD')),
                ('available', models.BooleanField(default=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='catalog.brand')),
                ('car_motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Motor', to='catalog.motor')),
            ],
            options={
                'ordering': ('car_brand',),
            },
        ),
    ]
