# Generated by Django 4.0.4 on 2022-06-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='age',
            field=models.IntegerField(default='', help_text='Введите возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='passport_number',
            field=models.CharField(help_text='Введите номер паспорта', max_length=7),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='passport_series',
            field=models.CharField(help_text='Введите серию паспорта', max_length=2),
        ),
    ]
