# Generated by Django 4.0.4 on 2022-06-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0002_personal_info_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='age',
        ),
    ]
